version: '3'
services: 
  cadet_app:
    container_name: "cadet_app"
    image: appcadet:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://bd_posgresql:5432/cadetarija
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=cadet.2024
    depends_on:
     -  bd_posgresql
  bd_posgresql:   
    container_name: "cadet_bd"
    image: postgres:11
    restart: always
#    expose:
#      - "5435"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cadet.2024
      POSTGRES_DB: cadetarija
#    command: -p 5432
#      POSTGRES_PORT: 5435
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "cadet.2024" 
    ports:
      - "80:80"
    depends_on:
      - bd_posgresql
    
